'''
Common schema names
'''

vendor_id_property = 'vendor_id'
taxi_company_property = 'taxi_company'
pickup_datetime_property = 'pickup_datetime'
dropoff_datetime_property = 'dropoff_datetime'
pickup_location_id_property = 'pickup_location_id'
dropoff_location_id_property = 'dropoff_location_id'
passenger_count_property = 'passenger_count'
trip_distance_property = 'trip_distance'
store_and_forward_flag_property = 'store_and_forward_flag'
ratecode_id_property = 'ratecode_id'
fare_amount_property = 'fare_amount'
tolls_amount_property = 'tolls_amount'
total_amount_property = 'total_amount'
mta_tax_property = 'mta_tax'
improvement_surcharge_property = 'improvement_surcharge'
extra_property = 'extra'
tip_amount_property = 'tip_amount'
payment_type_property = 'payment_type'